### ISSUE TITLE
Add link to the logo image

### ISSUE THREAD

**Issue by JuricDavor** [hellofresh/janus-dashboard#139]
![pasted image at 2017_11_02 05_47 pm](https://user-images.githubusercontent.com/15127945/32338969-9c0e9d36-bff6-11e7-9d8b-8ca745c5e8d5.png)

Can we add a link to the logo image so it redirects to APi's definition list or maybe Janus project page. What do you think, @italolelis ?

**Comment by italolelis** [comment]
Yes we should do that 👍

**Comment by ivanzusko** [comment]
@italolelis but which of this `to APi's definition list` or `maybe Janus project page`? 😄

**Comment by italolelis** [comment]
To the `APi's definition list`

**Comment by ivanzusko** [comment]
Obrigado, @italolelis
