### ISSUE TITLE
Add validation for OAuth Server Name

### ISSUE THREAD

**Issue by JuricDavor** [hellofresh/janus-dashboard#181]
[Add validation for OAuth Server Name. if you add a name of a server which already exist you are able to save that changes. Although the server is not created you are receiving a popup with a success message ]

**Reproduction Steps:**

1. [Log in > Navigate to OAuth Servers]
2. [Create a new OAuth Servers]
3. [Fill OAuth **Server Name** input field which already exist ]

**User should not be able to save changes. Error message should appear in a popup that this Server Name already exist:**

[Describe expected behavior here]

**When clicking on Create a OAuth Server popup appears with the successful message. Although the actual server is not created we should not show popup with successful message.**

![oath server 1](https://user-images.githubusercontent.com/15127945/32720648-79ae9b44-c864-11e7-97a3-4a5a032632b3.png)
![oauth server 4](https://user-images.githubusercontent.com/15127945/32720669-82bd0c20-c864-11e7-945f-23ee08056e63.png)
![oauth server 3](https://user-images.githubusercontent.com/15127945/32720662-800d7ff0-c864-11e7-976f-e8d5365d2bac.png)
![oauth server 2](https://user-images.githubusercontent.com/15127945/32720655-7d6977fe-c864-11e7-9eae-df96ea35c95b.png)

**Comment by ivanzusko** [comment]
Thank you, @JuricDavor !

**Comment by ivanzusko** [comment]
@rafaeljesus , Senior, por favor, can you check this out? Seems like when we are creating the new item with the same name - it's merging to elements into one...

**Comment by s4nji** [comment]
@ivanzusko the issue you mentioned has been fixed 🙂

**Comment by ivanzusko** [comment]
Awesome! 🎉
