### ISSUE TITLE
Wrong title displays when trying to clone existing API

### ISSUE THREAD

**Issue by JuricDavor** [hellofresh/janus-dashboard#182]
[When trying to clone existing API, we are redirected to **New** url but the title of the page is _Edit API_ .]

**Reproduction Steps:**

1. [Log in > Navigate to Api Definitions]
2. [Click on Clone icon next to existing API]

[Describe expected behavior here]

**Title of the page should be _Create New API_:**

![clone existing api 1](https://user-images.githubusercontent.com/15127945/32721887-51a74ea8-c868-11e7-827a-8a1b26e53b59.png)

![clone api 2](https://user-images.githubusercontent.com/15127945/32721891-5629b966-c868-11e7-85cd-59e67c9d00a0.png)

**Comment by ivanzusko** [comment]
Thank you, @JuricDavor !

**Comment by ivanzusko** [comment]
resolved in **PR** https://github.com/hellofresh/janus-dashboard/pull/189
