### ISSUE TITLE
Do not display inactive Api's on Healthcheck page

### ISSUE THREAD

**Issue by JuricDavor** [hellofresh/janus-dashboard#203]
[Inactive API's appears on Health check page. We should only show Active APi's on Health Check page.]

**Reproduction Steps:**

1. [Log in to Janus]
2. [Search for an inactive API `davor-qa-dj`]
3. [Verify that the APi is not Active]
4. [Navigate to Healthcheck page (API appears on the list)]

**Expected behavior:**

[We should only show Active APi's on Health Check page. ]

**Observed behavior:**

[[Inactive API's appears on Health check page]

<img width="1263" alt="healthcheck 01" src="https://user-images.githubusercontent.com/15127945/32888399-6e789300-cac7-11e7-9f8c-315f34a9f31c.png">
<img width="1279" alt="healthcheck 02" src="https://user-images.githubusercontent.com/15127945/32888410-73b096d8-cac7-11e7-8f40-8db9e9295273.png">
<img width="1226" alt="healthecheck 03" src="https://user-images.githubusercontent.com/15127945/32888416-778dbf56-cac7-11e7-91ad-063e003fdad9.png">

**Comment by ivanzusko** [comment]
@rafaeljesus , is there a way to not send me inactive stuff? 😄

**Comment by rafaeljesus** [comment]
@JuricDavor it should be fixed on this PR https://github.com/hellofresh/janus/pull/239 can you please test again?

**Comment by JuricDavor** [comment]
+1

**Comment by s4nji** [comment]
Can confirm that inactive endpoints don't show up in healthcheck page anymore, closing issue.
