### ISSUE TITLE
Make Api Names clickable on Health Check page

### ISSUE THREAD

**Issue by JuricDavor** [hellofresh/janus-dashboard#205]
[Make Api Names clickable on Health Check page]

**Reproduction Steps:**

1. [Log in to Janus]
2. [Navigate to Healthcheck page]
3. [Click on API name which appears on the list ]

**Expected behavior:**

[User should be redirected to Edit page of that specific API ]

**Observed behavior:**

[Nothing happens the name of the API is not clickable]
<img width="1226" alt="healthecheck 03" src="https://user-images.githubusercontent.com/15127945/32889282-90c953b0-caca-11e7-904f-27f05c269e3b.png">

**Comment by ivanzusko** [comment]
Resolved

**Comment by JuricDavor** [comment]
+1
