### ISSUE TITLE
Create Sticky Top Navigation (action buttons)

### ISSUE THREAD

**Issue by JuricDavor** [hellofresh/janus-dashboard#210]
[Create Sticky Top navigation (Action buttons - Save, Copy, Delete button at least). Since APIs and Oauth Servers will be long pages with a lot of plugins and request users will have to scroll down an app to Save/Delete/Clone. We should add sticky top navigation for action buttons, so users can perform changes without scrolling up or down for confirmation or any other changes.]

As a inspiration believe it or not we have decided to look at our BOB :-) 

Screenshots attached:

![bob 1](https://user-images.githubusercontent.com/15127945/32898040-5a87104a-cae7-11e7-8c1e-17c1ed6ae34e.png)
![bob 2](https://user-images.githubusercontent.com/15127945/32898046-5eb8f624-cae7-11e7-96ea-40828d6da480.png)

**Comment by ivanzusko** [comment]
Nice idea, @JuricDavor 👍 
But I'd like to see them on the side... on the dark side 🕶
