### ISSUE TITLE
View page

### ISSUE THREAD

**Issue by alileza** [hellofresh/janus-dashboard#213]
I would suggest to have a view page, to see detail instead of using edit page

**Comment by ivanzusko** [comment]
First of all, thank you for your contribution, @alileza:+1: .
Second, we will have a role system, so only those who will have permissions will be able to edit info. Others will see **readonly** view 😉

**Comment by alileza** [comment]
I believe View Page is not only important for Unauthorized people, but also to prevent unintended changes that happens during view. But if you don't think that's necessary, feel free to close this ticket

**Comment by rafaeljesus** [comment]
Yes definitely agree to have a view page, we had discussed this already and are going to allow users view the proxy contents on the view page rather than edit which is not intuitive at all

**Comment by JuricDavor** [comment]
+1

**Comment by ivanzusko** [comment]
I think it will be the same page, just with additional button `Edit` on top (where all buttons like `Save` and `Delete` usually stay).
