### ISSUE TITLE
Users are not able to edit Oauth Server and Save changes

### ISSUE THREAD

**Issue by JuricDavor** [hellofresh/janus-dashboard#223]
[Users are not able to edit Oauth Server and Save changes. Also if you enter in existing Oauth Server and you not make any changes and click on Save button you got 409 Conflict]

**Reproduction Steps:**

1. [Log in to Janus]
2. [Navigate to Oauth Servers]
3. [Click on Edit icon next to first existing Oauth Server on the list]
4. [Scroll down at the bottom and click on Save button without making any changes]
5. [Or you can change any of radio buttons and click on Save button]

**Expected behavior:**

[Users should be able to edit existing Oauth Servers and Save changes. ]

**Observed behavior:**

[Editing existing Oauth Server and clicking on Save button returns modal with message: _oauth server name is already registered_]

![oauth server 1](https://user-images.githubusercontent.com/15127945/33021592-b3c0d0ba-ce02-11e7-8f7a-8b4012abdc6e.png)
![o auth server 2](https://user-images.githubusercontent.com/15127945/33021599-b905e02e-ce02-11e7-8f57-d7ada13e75ac.png)
![oauth server 3](https://user-images.githubusercontent.com/15127945/33021614-bc4ea6b2-ce02-11e7-8090-ab5462c720fe.png)

**Comment by s4nji** [comment]
This should be fixed when #216 is merged.
