### ISSUE TITLE
Unable to log in dashboard？

### ISSUE THREAD

**Issue by younglifestyle** [hellofresh/janus-dashboard#306]
use user:admin，password: admin，Program appears Request failed with status code 405

**Comment by plinio-cardoso** [comment]
Did you add the `Janus Admin URL`? If not, please add `http://localhost:8081`. Just make sure it doesn't contain the trailing slash in the URL. 

Example: 
![screen shot 2018-10-26 at 11 13 54](https://user-images.githubusercontent.com/35220857/47560491-411e2980-d910-11e8-9dd1-7be646df592d.png)
