### ISSUE TITLE
Error building project 

### ISSUE THREAD

**Issue by vivekimsit** [hellofresh/janus-dashboard#45]
I tried to clone and build to project on my machine but fails to build using my local node installation:

```
❯ make
==> Installing dependencies using dockerized node
/bin/sh: docker: command not found
make: *** [deps-docker] Error 127


```

I think as per the doc it should not use docker option.

**Comment by s4nji** [comment]
Executing `make` without any additional arguments runs the [default goal](https://www.gnu.org/software/make/manual/html_node/How-Make-Works.html) which is the `docker-deps`.

To install the project without docker with the Makefile, you will need to run `make all`.
